--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/adams-pm-plugins/BuycraftPM
build-by-default: true
branches:
- v3.0
projects:
  BuycraftPM:
    path: ""
    libs:
      - src: muqsit/InvMenu/InvMenu
        version: ^3.1.1
...
